[project]
name = "bulwark"
description = "Oracle safety for Bitcoin DeFi on Stacks"
authors = []
telemetry = false
cache_dir = "./.cache"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

[contracts.price-policy]
path = "contracts/price-policy.clar"
clarity_version = 3
epoch = "3.0"

[contracts.pyth-traits-v2]
path = "contracts/pyth-traits-v2.clar"
clarity_version = 3
epoch = "3.0"

[contracts.mock-pyth-storage]
path = "contracts/mock-pyth-storage.clar"
clarity_version = 3
epoch = "3.0"

[contracts.fake-pyth-storage]
path = "contracts/fake-pyth-storage.clar"
clarity_version = 3
epoch = "3.0"

[contracts.oracle-guard]
path = "contracts/oracle-guard.clar"
clarity_version = 3
epoch = "3.0"

[contracts.price-source-trait]
path = "contracts/price-source-trait.clar"
clarity_version = 3
epoch = "3.0"

[contracts.trait-caller]
path = "contracts/trait-caller.clar"
clarity_version = 3
epoch = "3.0"
