import { defineConfig } from "vitest/config";
import { vitestSetupFilePath } from "@hirosystems/clarinet-sdk/vitest";

// Runs tests-mainnet/ against the forked project generated by
// scripts/build-mainnet-fork.mjs. Needs network access to the Hiro API.
export default defineConfig({
  test: {
    environment: "clarinet",
    pool: "forks",
    poolOptions: { forks: { singleFork: true } },
    include: ["tests-mainnet/**/*.test.ts"],
    setupFiles: [vitestSetupFilePath],
    testTimeout: 120_000,
    hookTimeout: 120_000,
    environmentOptions: {
      clarinet: { manifestPath: "./.mainnet-fork/Clarinet.toml" },
    },
  },
});
