import { defineConfig } from "vitest/config";
import { vitestSetupFilePath } from "@hirosystems/clarinet-sdk/vitest";

// Runs one named fork at a time (FORK=state|replay). Each fork is a project
// generated by scripts/build-mainnet-fork.mjs. Needs network access to the Hiro API.
const fork = process.env.FORK ?? "state";

export default defineConfig({
  test: {
    environment: "clarinet",
    pool: "forks",
    poolOptions: { forks: { singleFork: true } },
    include: [`tests-mainnet/${fork}/**/*.test.ts`],
    setupFiles: [vitestSetupFilePath],
    testTimeout: 120_000,
    hookTimeout: 120_000,
    environmentOptions: {
      clarinet: { manifestPath: `./.mainnet-fork/${fork}/Clarinet.toml` },
    },
  },
});
